/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file zip-module.h zip module header file */
/*
    Qore zip module

    Copyright (C) 2026 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef _QORE_ZIP_MODULE_H
#define _QORE_ZIP_MODULE_H

#include <qore/Qore.h>
#include <qore/QoreSandboxManager.h>
#include <mz.h>
#include <mz_zip.h>
#include <mz_strm.h>
#include <mz_strm_mem.h>
#include <mz_strm_os.h>
#include <mz_zip_rw.h>

// Forward declarations
class QoreZipFile;

// Hashdecl init functions (generated by QPP from QC_ZipFile.qpp)
DLLLOCAL TypedHashDecl* init_hashdecl_ZipEntryInfo(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_ZipAddOptions(QoreNamespace& ns);
DLLLOCAL TypedHashDecl* init_hashdecl_ZipExtractOptions(QoreNamespace& ns);

// Compression methods
#define ZIP_CM_STORE        MZ_COMPRESS_METHOD_STORE
#define ZIP_CM_DEFLATE      MZ_COMPRESS_METHOD_DEFLATE
#define ZIP_CM_BZIP2        MZ_COMPRESS_METHOD_BZIP2
#define ZIP_CM_LZMA         MZ_COMPRESS_METHOD_LZMA
#define ZIP_CM_ZSTD         MZ_COMPRESS_METHOD_ZSTD
#define ZIP_CM_XZ           MZ_COMPRESS_METHOD_XZ

// Compression levels
#define ZIP_COMPRESSION_DEFAULT MZ_COMPRESS_LEVEL_DEFAULT
#define ZIP_COMPRESSION_STORE   0
#define ZIP_COMPRESSION_FASTEST 1
#define ZIP_COMPRESSION_BEST    9

// Encryption methods
#define ZIP_EM_NONE         MZ_AES_ENCRYPTION_MODE_NONE
#define ZIP_EM_TRAD_PKWARE  MZ_AES_ENCRYPTION_MODE_PKWARE
#define ZIP_EM_AES_128      MZ_AES_ENCRYPTION_MODE_128
#define ZIP_EM_AES_192      MZ_AES_ENCRYPTION_MODE_192
#define ZIP_EM_AES_256      MZ_AES_ENCRYPTION_MODE_256

// Global hashdecl pointers (initialized in zip-module.cpp)
extern const TypedHashDecl* hashdeclZipEntryInfo;
extern const TypedHashDecl* hashdeclZipAddOptions;
extern const TypedHashDecl* hashdeclZipExtractOptions;

// Namespace
extern QoreNamespace ZipNS;

#endif // _QORE_ZIP_MODULE_H
